# Generated by Django 5.0.6 on 2024-07-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu_service", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MenuItem",
        ),
    ]
